"""create vacations for employees

Revision ID: 0f013c3adc4f
Revises: 27bf2aa3b8c7
Create Date: 2024-12-21 16:31:10.022487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f013c3adc4f'
down_revision = '27bf2aa3b8c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('employee', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'updated_at')
    op.drop_column('employee', 'created_at')
    # ### end Alembic commands ###
