"""add vacations type

Revision ID: 24007b398349
Revises: d6eb6a4f967c
Create Date: 2024-12-22 16:52:39.998203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24007b398349'
down_revision = 'd6eb6a4f967c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacation', sa.Column('vacation_type', sa.String(), nullable=False))
    op.alter_column('vacation', 'employee_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacation', 'employee_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('vacation', 'vacation_type')
    # ### end Alembic commands ###
